apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  namespace: production
  labels:
    app: payroll-service
spec:
  type: LoadBalancer
  selector:
    app: payroll-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
